-- Idempotent SQL script for Supabase SQL Editor

-- 1. Table for Comment-to-DM Automation Rules (ig_dm_rules)
create table if not exists ig_dm_rules (
  id text primary key,
  name text,
  type text default 'comment',
  media_id text,
  keywords text[] default '{}',
  match_type text default 'contains',
  public_reply text,
  dm_reply text,
  active boolean default true,
  created_at timestamp with time zone default now()
);

-- Ensure columns exist if the table was created previously without them
alter table ig_dm_rules add column if not exists type text default 'comment';
alter table ig_dm_rules add column if not exists media_id text;
alter table ig_dm_rules add column if not exists keywords text[] default '{}';
alter table ig_dm_rules add column if not exists match_type text default 'contains';
alter table ig_dm_rules add column if not exists public_reply text;
alter table ig_dm_rules add column if not exists dm_reply text;
alter table ig_dm_rules add column if not exists active boolean default true;
alter table ig_dm_rules add column if not exists name text;

-- 2. Table for Instagram Messages & Unified Inbox (ig_messages)
create table if not exists ig_messages (
  id bigint generated by default as identity primary key,
  igsid text not null,
  username text,
  direction text check (direction in ('in', 'out')),
  text text,
  is_ai boolean default false,
  created_at timestamp with time zone default now()
);

